{% set name = "hexwatershed" %}
{% set git_rev = "main" %}
{% set version = "0.2.30" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/changliao1025/pyhexwatershed
build:  
  noarch: python 
  number: 1
requirements:  
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - python >=3.8    
    - setuptools
    - pip
  host:
    - python {{ python_min }}
    - pip
    - {{ compiler('cxx') }}
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - gdal
    - pyflowline
test:
  requires:
    - python {{ python_min }}
  imports:
    - pyhexwatershed
about:
  home: https://github.com/changliao1025/pyhexwatershed
  summary: A mesh-independent flow direction model for hydrologic models
  license: BSD-3-Clause
  license_file: LICENSE.md
extra:
  recipe-maintainers:
    - changliao1025
